export const SELECT_ACCOUNT = 'SELECT_ACCOUNT';
export const REQUEST_TRANSACTIONS = 'REQUEST_TRANSACTIONS';
export const RECEIVE_TRANSACTIONS = 'RECEIVE_TRANSACTIONS';
export const ERROR_TRANSACTIONS = 'ERROR_TRANSACTIONS';
